basic:
  seed: 233
  GPU: 0
  debug: False
  id: 'unnamed'
  mode: train
  search: False
  amp: 'Native'

experiment:
  name: 'AnnotatedRandomKTrainTestSplit'
  random_state: 233
  run_fold: -1
  batch_sampler: False
  weight: False
  preprocess: JPEG_512_pan
  image_only: True
  skip_outlier: True
  outlier: train
  anno_only: False
  keep_valid: True

data:
  image_prefix: 'png_512'
  pl: 'demo'
  pl_file: 'train_oof_pl_sheep.csv'
  mask_oof_path: train_ensemble_mask_0731

model:
  name: 'v2m_aux'
  from_checkpoint: '/home/featurize/siim/results/aux_bce_agg_exp_rot_30_20_pl.upload/checkpoints/f{}_epoch.pth'
  out_feature: 4
  params:
    dropout: 0.5
    pretrained: True
    pool: gem

train:
  dir: '../results'
  batch_size: 24
  num_epochs: 4
  cutmix: False
  beta: 1
  cutmix_prob: 0.5
  cutmix_prob_increase: 0
  validations_round: 1
  freeze_backbond: 1
  freeze_top_layer_groups: 0
  freeze_start_epoch: 0

eval:
  batch_size: 32

loss:
  name: 'bce'
  seg_weight: 40
  eps: 0.1
  params:
    reduction: 'none'

optimizer:
  name: 'Adam'
  step: 1
  params:
    lr: 0.0002
    weight_decay: 0

scheduler:
  name: 'CosineAnnealingLR'
  warm_up: True
  params:
    factor: 0.2
    patience: 10

transform:
#  name: 's_0627/sin_512_final_hflip_cut1_ssr7_r30'
#  val_name: ''
  name: 'hflip'
  num_preprocessor: 8
  size: 512
