#!/bin/bash

#SBATCH --job-name=folds            # Job name
#SBATCH --output=job.%j.out         # Name of output file
#SBATCH --cpus-per-task=2           # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=2:00:00              # Run time (hh:mm:ss) - run for 2 hours max
#SBATCH --partition=brown           # Run on either the Red or Brown queue
#SBATCH --mail-type=BEGIN,FAIL,END

# make folds
cd ..
python create_folds.py
