__version__: 0.5.2
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.augmentations.transforms.RandomResizedCrop
    always_apply: false
    height: 300
    interpolation: 1
    p: 1
    ratio:
    - 0.75
    - 1.3333333333333333
    scale:
    - 0.9
    - 1
    width: 300
  - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: albumentations.augmentations.transforms.ShiftScaleRotate
    always_apply: false
    border_mode: 4
    interpolation: 1
    mask_value: null
    p: 0.5
    rotate_limit:
    - -45
    - 45
    scale_limit:
    - -0.09999999999999998
    - 0.10000000000000009
    shift_limit_x:
    - -0.0625
    - 0.0625
    shift_limit_y:
    - -0.0625
    - 0.0625
    value: null
  - __class_fullname__: albumentations.augmentations.transforms.HueSaturationValue
    always_apply: false
    hue_shift_limit:
    - -10
    - 10
    p: 0.7
    sat_shift_limit:
    - -10
    - 10
    val_shift_limit:
    - -10
    - 10
  - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
    always_apply: false
    brightness_by_max: true
    brightness_limit: &id001
    - -0.2
    - 0.2
    contrast_limit: *id001
    p: 0.7
  - __class_fullname__: albumentations.augmentations.transforms.CLAHE
    always_apply: false
    clip_limit:
    - 1
    - 4
    p: 0.5
    tile_grid_size:
    - 8
    - 8
  - __class_fullname__: albumentations.core.composition.OneOf
    p: 0.2
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.OpticalDistortion
      always_apply: false
      border_mode: 4
      distort_limit:
      - -1.0
      - 1.0
      interpolation: 1
      mask_value: null
      p: 0.5
      shift_limit:
      - -0.05
      - 0.05
      value: null
    - __class_fullname__: albumentations.augmentations.transforms.GridDistortion
      always_apply: false
      border_mode: 4
      distort_limit:
      - -1.0
      - 1.0
      interpolation: 1
      mask_value: null
      num_steps: 5
      p: 0.5
      value: null
    - __class_fullname__: albumentations.augmentations.transforms.ElasticTransform
      alpha: 3
      alpha_affine: 50
      always_apply: false
      approximate: false
      border_mode: 4
      interpolation: 1
      mask_value: null
      p: 0.5
      sigma: 50
      value: null
  - __class_fullname__: albumentations.augmentations.transforms.Resize
    always_apply: false
    height: 300
    interpolation: 1
    p: 1
    width: 300
  - __class_fullname__: albumentations.augmentations.transforms.Normalize
    always_apply: false
    max_pixel_value: 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    p: 1.0
    std:
    - 0.229
    - 0.224
    - 0.225
