__version__: 0.4.3
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.core.composition.OneOf
    p: 0.5
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
      always_apply: false
      p: 0.5
    - __class_fullname__: albumentations.augmentations.transforms.VerticalFlip
      always_apply: false
      p: 0.5
  - __class_fullname__: albumentations.augmentations.transforms.CenterCrop
    always_apply: false
    height: 624
    p: 1.0
    width: 624
