__version__: 0.4.5
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
    always_apply: false
    height: 448
    p: 1.0
    width: 448
  - __class_fullname__: albumentations.core.composition.Compose
    additional_targets: {}
    bbox_params: null
    keypoint_params: null
    p: 1.0
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.Cutout
      always_apply: false
      max_h_size: 8
      max_w_size: 8
      num_holes: 8
      p: 0.5
    - __class_fullname__: albumentations.augmentations.transforms.RandomRotate90
      always_apply: false
      p: 0.5
    - __class_fullname__: albumentations.augmentations.transforms.Flip
      always_apply: false
      p: 0.5
    - __class_fullname__: albumentations.core.composition.OneOf
      p: 0.5
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        always_apply: false
        brightness_by_max: true
        brightness_limit:
        - -0.2
        - 0.2
        contrast_limit:
        - -0.2
        - 0.2
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.HueSaturationValue
        always_apply: false
        hue_shift_limit:
        - -20
        - 20
        p: 0.5
        sat_shift_limit:
        - -50
        - 50
        val_shift_limit:
        - -50
        - 50
    - __class_fullname__: albumentations.core.composition.OneOf
      p: 0.5
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.MotionBlur
        always_apply: false
        blur_limit:
        - 3
        - 7
        p: 0.2
      - __class_fullname__: albumentations.augmentations.transforms.MedianBlur
        always_apply: false
        blur_limit:
        - 3
        - 3
        p: 0.1
      - __class_fullname__: albumentations.augmentations.transforms.Blur
        always_apply: false
        blur_limit:
        - 3
        - 3
        p: 0.1
    - __class_fullname__: albumentations.augmentations.transforms.ShiftScaleRotate
      always_apply: false
      border_mode: 4
      interpolation: 1
      mask_value: null
      p: 0.5
      rotate_limit:
      - -45
      - 45
      scale_limit:
      - -0.19999999999999996
      - 0.19999999999999996
      shift_limit:
      - -0.0625
      - 0.0625
      value: null
    - __class_fullname__: albumentations.core.composition.OneOf
      p: 0.5
      transforms:
      - __class_fullname__: albumentations.augmentations.transforms.OpticalDistortion
        always_apply: false
        border_mode: 4
        distort_limit:
        - -0.05
        - 0.05
        interpolation: 1
        mask_value: null
        p: 0.3
        shift_limit:
        - -0.05
        - 0.05
        value: null
      - __class_fullname__: albumentations.augmentations.transforms.GridDistortion
        always_apply: false
        border_mode: 4
        distort_limit:
        - -0.3
        - 0.3
        interpolation: 1
        mask_value: null
        num_steps: 5
        p: 0.1
        value: null
      - __class_fullname__: albumentations.imgaug.transforms.IAAPiecewiseAffine
        always_apply: false
        cval: 0
        mode: constant
        nb_cols: 4
        nb_rows: 4
        order: 1
        p: 0.3
        scale:
        - 0.03
        - 0.05
