__version__: 0.5.2
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.augmentations.transforms.RandomResizedCrop
    always_apply: false
    height: 512
    interpolation: 1
    p: 1
    ratio:
    - 0.75
    - 1.3333333333333333
    scale:
    - 0.9
    - 1
    width: 512
  - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: albumentations.augmentations.transforms.ShiftScaleRotate
    always_apply: false
    border_mode: 4
    interpolation: 1
    mask_value: null
    p: 0.5
    rotate_limit:
    - -45
    - 45
    scale_limit:
    - -0.09999999999999998
    - 0.10000000000000009
    shift_limit_x:
    - -0.0625
    - 0.0625
    shift_limit_y:
    - -0.0625
    - 0.0625
    value: null
  - __class_fullname__: albumentations.augmentations.transforms.HueSaturationValue
    always_apply: false
    hue_shift_limit:
    - -10
    - 10
    p: 0.7
    sat_shift_limit:
    - -10
    - 10
    val_shift_limit:
    - -10
    - 10
  - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
    always_apply: false
    brightness_by_max: true
    brightness_limit: &id001
    - -0.2
    - 0.2
    contrast_limit: *id001
    p: 0.7
  - __class_fullname__: albumentations.augmentations.transforms.CLAHE
    always_apply: false
    clip_limit:
    - 1
    - 4
    p: 0.5
    tile_grid_size:
    - 8
    - 8
  - __class_fullname__: albumentations.core.composition.OneOf
    p: 0.2
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.OpticalDistortion
      always_apply: false
      border_mode: 4
      distort_limit:
      - -1.0
      - 1.0
      interpolation: 1
      mask_value: null
      p: 0.5
      shift_limit:
      - -0.05
      - 0.05
      value: null
    - __class_fullname__: albumentations.augmentations.transforms.GridDistortion
      always_apply: false
      border_mode: 4
      distort_limit:
      - -1.0
      - 1.0
      interpolation: 1
      mask_value: null
      num_steps: 5
      p: 0.5
      value: null
    - __class_fullname__: albumentations.augmentations.transforms.ElasticTransform
      alpha: 3
      alpha_affine: 50
      always_apply: false
      approximate: false
      border_mode: 4
      interpolation: 1
      mask_value: null
      p: 0.5
      sigma: 50
      value: null
  - __class_fullname__: albumentations.core.composition.OneOf
    p: 0.2
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.GaussNoise
      always_apply: false
      p: 0.5
      var_limit:
      - 10
      - 50
    - __class_fullname__: albumentations.augmentations.transforms.GaussianBlur
      always_apply: false
      blur_limit:
      - 3
      - 7
      p: 0.5
      sigma_limit:
      - 0
      - 0
    - __class_fullname__: albumentations.augmentations.transforms.MotionBlur
      always_apply: false
      blur_limit:
      - 3
      - 7
      p: 0.5
    - __class_fullname__: albumentations.augmentations.transforms.MedianBlur
      always_apply: false
      blur_limit:
      - 3
      - 7
      p: 0.5
  - __class_fullname__: albumentations.augmentations.transforms.Resize
    always_apply: false
    height: 512
    interpolation: 1
    p: 1
    width: 512
  - __class_fullname__: albumentations.core.composition.OneOf
    p: 0.2
    transforms:
    - __class_fullname__: albumentations.augmentations.transforms.JpegCompression
      always_apply: false
      p: 0.5
      quality_lower: 99
      quality_upper: 100
    - __class_fullname__: albumentations.augmentations.transforms.Downscale
      always_apply: false
      interpolation: 0
      p: 0.5
      scale_max: 0.15
      scale_min: 0.1
  - __class_fullname__: albumentations.imgaug.transforms.IAAPiecewiseAffine
    always_apply: false
    cval: 0
    mode: constant
    nb_cols: 4
    nb_rows: 4
    order: 1
    p: 0.2
    scale:
    - 0.03
    - 0.05
  - __class_fullname__: albumentations.imgaug.transforms.IAASharpen
    alpha:
    - 0.2
    - 0.5
    always_apply: false
    lightness:
    - 0.5
    - 1.0
    p: 0.2
  - __class_fullname__: albumentations.augmentations.transforms.Cutout
    always_apply: false
    max_h_size: 51
    max_w_size: 51
    num_holes: 5
    p: 0.0
