__version__: 0.4.6
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.augmentations.transforms.RandomResizedCrop
    always_apply: false
    height: 768
    interpolation: 1
    p: 1
    ratio: [0.75, 1.3333333333333333]
    scale: [0.08, 1.0]
    width: 768
  - __class_fullname__: albumentations.augmentations.transforms.ShiftScaleRotate
    always_apply: false
    border_mode: 4
    interpolation: 1
    mask_value: null
    p: 0.5
    rotate_limit: [-45, 45]
    scale_limit: [-0.09999999999999998, 0.10000000000000009]
    shift_limit: [-0.0625, 0.0625]
    value: null
  - __class_fullname__: albumentations.augmentations.transforms.HueSaturationValue
    always_apply: false
    hue_shift_limit: [-20, 20]
    p: 0.7
    sat_shift_limit: [-20, 20]
    val_shift_limit: [-20, 20]
  - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
    always_apply: false
    brightness_by_max: true
    brightness_limit: [-0.2, 0.2]
    contrast_limit: [-0.2, 0.2]
    p: 0.7
  - __class_fullname__: albumentations.augmentations.transforms.Normalize
    always_apply: false
    max_pixel_value: 255.0
    mean: [0.485, 0.456, 0.406]
    p: 1.0
    std: [0.229, 0.224, 0.225]
